#   *******************************************************************
# -*- coding: utf-8 -*-

#   *******************************************************************
#   Updated Qt5/Qt6 imports to be used with generated file from
#   PyQt UI code generator
#   Enables either pyqt5, pyqt6 or PySide2 modules to be used
#   *******************************************************************

import importlib.util

if importlib.util.find_spec("PyQt"):
    # from PyQt import uic, loadUi
    # from PyQt import   QtCore
    from PyQt import (
        pyqt, QObject, QCoreApplication, QSettings,
        Qt, QSize, QRect, QMetaObject,
        Signal, Slot,
        QIcon, QPixmap, QImage, QFont,
        QApplication, QMainWindow, QWidget, QFrame,
        QDialog, QMessageBox, QFileDialog,
        QLayout, QFormLayout, QGridLayout,
        QVBoxLayout, QHBoxLayout,
        QSizePolicy, QSpacerItem,
        QAbstractItemView, QAbstractScrollArea, QScrollArea,
        QLabel, QLineEdit, QPlainTextEdit,
        QPushButton, QToolButton, QListWidget, QListWidgetItem,
        QProgressBar, QMenuBar, QStatusBar,
        QMenu, QAction,
        QDomDocument, QDomElement, QTextCursor)
else:
    # from .PyQt import uic, loadUi
    # from .PyQt import   QtCore
    from .PyQt import (
        pyqt, QObject, QCoreApplication, QSettings,
        Qt, QSize, QRect, QMetaObject,
        Signal, Slot,
        QIcon, QPixmap, QImage, QFont,
        QApplication, QMainWindow, QWidget, QFrame,
        QDialog, QMessageBox, QFileDialog,
        QLayout, QFormLayout, QGridLayout,
        QVBoxLayout, QHBoxLayout,
        QSizePolicy, QSpacerItem,
        QAbstractItemView, QAbstractScrollArea, QScrollArea,
        QLabel, QLineEdit, QPlainTextEdit,
        QPushButton, QToolButton, QListWidget, QListWidgetItem,
        QProgressBar, QMenuBar, QStatusBar,
        QMenu, QAction,
        QDomDocument, QDomElement, QTextCursor)

#   *******************************************************************
# Form implementation generated from reading ui file 'linz_schema_loader_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 476)
        MainWindow.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        MainWindow.setWindowTitle("")
        icon = QIcon()
        icon.addPixmap(QPixmap("../images/icon.svg"), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(parent=MainWindow)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logField = QPlainTextEdit(parent=self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logField.sizePolicy().hasHeightForWidth())
        self.logField.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily("Monospace")
        self.logField.setFont(font)
        self.logField.setStyleSheet("background-color: rgb(224, 255, 225);\n"
"color: rgb(0, 0, 0);")
        self.logField.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.logField.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.logField.setUndoRedoEnabled(False)
        self.logField.setLineWrapMode(QPlainTextEdit.LineWrapMode.WidgetWidth)
        self.logField.setReadOnly(True)
        self.logField.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.logField.setObjectName("logField")
        self.verticalLayout.addWidget(self.logField)
        self.statusFrame = QFrame(parent=self.centralwidget)
        self.statusFrame.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusFrame.sizePolicy().hasHeightForWidth())
        self.statusFrame.setSizePolicy(sizePolicy)
        self.statusFrame.setMinimumSize(QSize(0, 47))
        self.statusFrame.setMaximumSize(QSize(16777215, 47))
        self.statusFrame.setStyleSheet("background-color: rgb(239, 240, 241);\n"
"color: rgb(0, 115, 0);")
        self.statusFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.statusFrame.setFrameShadow(QFrame.Shadow.Sunken)
        self.statusFrame.setObjectName("statusFrame")
        self.horizontalLayout = QHBoxLayout(self.statusFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressLayout = QVBoxLayout()
        self.progressLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.progressLayout.setContentsMargins(-1, 2, -1, 2)
        self.progressLayout.setSpacing(3)
        self.progressLayout.setObjectName("progressLayout")
        self.layerLabel = QLabel(parent=self.statusFrame)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerLabel.sizePolicy().hasHeightForWidth())
        self.layerLabel.setSizePolicy(sizePolicy)
        self.layerLabel.setMinimumSize(QSize(0, 20))
        self.layerLabel.setMaximumSize(QSize(16777215, 20))
        self.layerLabel.setFrameShadow(QFrame.Shadow.Sunken)
        self.layerLabel.setText("")
        self.layerLabel.setIndent(3)
        self.layerLabel.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.layerLabel.setObjectName("layerLabel")
        self.progressLayout.addWidget(self.layerLabel)
        self.progressBar = QProgressBar(parent=self.statusFrame)
        self.progressBar.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QSize(0, 20))
        self.progressBar.setMaximumSize(QSize(16777215, 20))
        self.progressBar.setStyleSheet("background-color: rgb(255, 225, 175);\n"
"selection-background-color: rgb(170, 85, 0);\n"
"color: rgb(0, 0, 0);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.progressLayout)
        self.statusLayout = QVBoxLayout()
        self.statusLayout.setSizeConstraint(QLayout.SizeConstraint.SetFixedSize)
        self.statusLayout.setContentsMargins(-1, 2, -1, 2)
        self.statusLayout.setSpacing(3)
        self.statusLayout.setObjectName("statusLayout")
        self.progressLabel = QLabel(parent=self.statusFrame)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel.sizePolicy().hasHeightForWidth())
        self.progressLabel.setSizePolicy(sizePolicy)
        self.progressLabel.setMinimumSize(QSize(220, 20))
        self.progressLabel.setMaximumSize(QSize(220, 20))
        self.progressLabel.setText("")
        self.progressLabel.setIndent(0)
        self.progressLabel.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.progressLabel.setObjectName("progressLabel")
        self.statusLayout.addWidget(self.progressLabel)
        self.RemainderLabel = QLabel(parent=self.statusFrame)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemainderLabel.sizePolicy().hasHeightForWidth())
        self.RemainderLabel.setSizePolicy(sizePolicy)
        self.RemainderLabel.setMinimumSize(QSize(220, 20))
        self.RemainderLabel.setMaximumSize(QSize(220, 20))
        self.RemainderLabel.setText("")
        self.RemainderLabel.setIndent(0)
        self.RemainderLabel.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.RemainderLabel.setObjectName("RemainderLabel")
        self.statusLayout.addWidget(self.RemainderLabel)
        self.horizontalLayout.addLayout(self.statusLayout)
        self.verticalLayout.addWidget(self.statusFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QRect(0, 0, 900, 30))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setMinimumSize(QSize(0, 30))
        self.menuBar.setMaximumSize(QSize(16777215, 30))
        font = QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("background-color: rgb(239, 240, 241);\n"
"font: 81 10pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(41, 128, 185);\n"
"selection-color: rgb(0, 0, 0);\n"
"")
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QMenu(parent=self.menuBar)
        font = QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.menuMain.setFont(font)
        self.menuMain.setObjectName("menuMain")
        self.menuSchemas = QMenu(parent=self.menuBar)
        font = QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.menuSchemas.setFont(font)
        self.menuSchemas.setObjectName("menuSchemas")
        self.menuLayers = QMenu(parent=self.menuBar)
        self.menuLayers.setObjectName("menuLayers")
        self.menuHelp = QMenu(parent=self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(parent=MainWindow)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMinimumSize(QSize(0, 0))
        self.statusBar.setMaximumSize(QSize(16777215, 0))
        self.statusBar.setStyleSheet("background-color: rgb(239, 240, 241);\n"
"color: rgb(0, 115, 0);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionConnect = QAction(parent=MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionSelectSchema = QAction(parent=MainWindow)
        self.actionSelectSchema.setObjectName("actionSelectSchema")
        self.actionExit = QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSchemasSchema = QAction(parent=MainWindow)
        self.actionSchemasSchema.setEnabled(False)
        self.actionSchemasSchema.setText("....")
        self.actionSchemasSchema.setToolTip(".")
        font = QFont()
        font.setItalic(True)
        self.actionSchemasSchema.setFont(font)
        self.actionSchemasSchema.setObjectName("actionSchemasSchema")
        self.actionCreateSchema = QAction(parent=MainWindow)
        self.actionCreateSchema.setObjectName("actionCreateSchema")
        self.actionUpdateSchema = QAction(parent=MainWindow)
        self.actionUpdateSchema.setObjectName("actionUpdateSchema")
        self.actionDropSchema = QAction(parent=MainWindow)
        self.actionDropSchema.setObjectName("actionDropSchema")
        self.actionLoadcsvData = QAction(parent=MainWindow)
        self.actionLoadcsvData.setObjectName("actionLoadcsvData")
        self.actionCreateIndexes = QAction(parent=MainWindow)
        self.actionCreateIndexes.setObjectName("actionCreateIndexes")
        self.actionCreateViews = QAction(parent=MainWindow)
        self.actionCreateViews.setObjectName("actionCreateViews")
        self.actionLayersSchema = QAction(parent=MainWindow)
        self.actionLayersSchema.setEnabled(False)
        self.actionLayersSchema.setText("....")
        self.actionLayersSchema.setToolTip(".")
        font = QFont()
        font.setItalic(True)
        self.actionLayersSchema.setFont(font)
        self.actionLayersSchema.setObjectName("actionLayersSchema")
        self.actionCreateLayers = QAction(parent=MainWindow)
        self.actionCreateLayers.setObjectName("actionCreateLayers")
        self.actionCreateRelations = QAction(parent=MainWindow)
        self.actionCreateRelations.setObjectName("actionCreateRelations")
        self.actionCreateTopoStyles = QAction(parent=MainWindow)
        self.actionCreateTopoStyles.setObjectName("actionCreateTopoStyles")
        self.actionAbout = QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QAction(parent=MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionLoadLayerStyles = QAction(parent=MainWindow)
        self.actionLoadLayerStyles.setObjectName("actionLoadLayerStyles")
        self.menuMain.addAction(self.actionConnect)
        self.menuMain.addAction(self.actionSelectSchema)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit)
        self.menuSchemas.addAction(self.actionSchemasSchema)
        self.menuSchemas.addSeparator()
        self.menuSchemas.addAction(self.actionCreateSchema)
        self.menuSchemas.addAction(self.actionUpdateSchema)
        self.menuSchemas.addAction(self.actionDropSchema)
        self.menuSchemas.addAction(self.actionLoadcsvData)
        self.menuSchemas.addAction(self.actionCreateIndexes)
        self.menuSchemas.addAction(self.actionCreateViews)
        self.menuLayers.addAction(self.actionLayersSchema)
        self.menuLayers.addSeparator()
        self.menuLayers.addAction(self.actionCreateLayers)
        self.menuLayers.addAction(self.actionCreateRelations)
        self.menuLayers.addAction(self.actionLoadLayerStyles)
        self.menuLayers.addAction(self.actionCreateTopoStyles)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuSchemas.menuAction())
        self.menuBar.addAction(self.menuLayers.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuSchemas.setTitle(_translate("MainWindow", "Database Schemas"))
        self.menuLayers.setTitle(_translate("MainWindow", "Map Layers"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionConnect.setText(_translate("MainWindow", "Connect to Database"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect to Database as Administrator"))
        self.actionSelectSchema.setText(_translate("MainWindow", "Select Schema"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreateSchema.setText(_translate("MainWindow", "Create Schema"))
        self.actionUpdateSchema.setText(_translate("MainWindow", "Update Schema"))
        self.actionDropSchema.setText(_translate("MainWindow", "Drop Schema"))
        self.actionLoadcsvData.setText(_translate("MainWindow", "Import *.csv Data"))
        self.actionCreateIndexes.setText(_translate("MainWindow", "Create Indexes"))
        self.actionCreateViews.setText(_translate("MainWindow", "Create Views"))
        self.actionCreateLayers.setText(_translate("MainWindow", "Create Map Layers"))
        self.actionCreateRelations.setText(_translate("MainWindow", "Define Relationships"))
        self.actionCreateTopoStyles.setText(_translate("MainWindow", "Create Topo Style Database"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionLoadLayerStyles.setText(_translate("MainWindow", "Define Layer Styles"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
