#   *******************************************************************
# -*- coding: utf-8 -*-

#   *******************************************************************
#   Updated Qt5/Qt6 imports to be used with generated file from
#   PyQt UI code generator
#   Enables either pyqt5, pyqt6 or PySide2 modules to be used
#   *******************************************************************

import importlib.util

if importlib.util.find_spec("PyQt"):
    # from PyQt import uic, loadUi
    # from PyQt import   QtCore
    from PyQt import (
        pyqt, QObject, QCoreApplication, QSettings,
        Qt, QSize, QRect, QMetaObject,
        Signal, Slot,
        QIcon, QPixmap, QImage, QFont,
        QApplication, QMainWindow, QWidget, QFrame,
        QDialog, QMessageBox, QFileDialog,
        QLayout, QFormLayout, QGridLayout,
        QVBoxLayout, QHBoxLayout,
        QSizePolicy, QSpacerItem,
        QAbstractItemView, QAbstractScrollArea, QScrollArea,
        QLabel, QLineEdit, QPlainTextEdit,
        QPushButton, QToolButton, QListWidget, QListWidgetItem,
        QProgressBar, QMenuBar, QStatusBar,
        QMenu, QAction,
        QDomDocument, QDomElement, QTextCursor)
else:
    # from .PyQt import uic, loadUi
    # from .PyQt import   QtCore
    from .PyQt import (
        pyqt, QObject, QCoreApplication, QSettings,
        Qt, QSize, QRect, QMetaObject,
        Signal, Slot,
        QIcon, QPixmap, QImage, QFont,
        QApplication, QMainWindow, QWidget, QFrame,
        QDialog, QMessageBox, QFileDialog,
        QLayout, QFormLayout, QGridLayout,
        QVBoxLayout, QHBoxLayout,
        QSizePolicy, QSpacerItem,
        QAbstractItemView, QAbstractScrollArea, QScrollArea,
        QLabel, QLineEdit, QPlainTextEdit,
        QPushButton, QToolButton, QListWidget, QListWidgetItem,
        QProgressBar, QMenuBar, QStatusBar,
        QMenu, QAction,
        QDomDocument, QDomElement, QTextCursor)

#   *******************************************************************
# Form implementation generated from reading ui file 'linz_schema_login_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(Qt.WindowModality.ApplicationModal)
        Dialog.resize(540, 290)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QSize(540, 290))
        Dialog.setMaximumSize(QSize(540, 290))
        Dialog.setBaseSize(QSize(540, 290))
        self.formLayoutWidget = QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QRect(0, 0, 541, 278))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinAndMaxSize)
        self.formLayout.setContentsMargins(5, 5, 5, 0)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.hostLabel = QLabel(parent=self.formLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostLabel.sizePolicy().hasHeightForWidth())
        self.hostLabel.setSizePolicy(sizePolicy)
        self.hostLabel.setMinimumSize(QSize(65, 32))
        self.hostLabel.setMaximumSize(QSize(65, 32))
        self.hostLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.hostLabel)
        self.hostField = QLineEdit(parent=self.formLayoutWidget)
        self.hostField.setMinimumSize(QSize(0, 32))
        self.hostField.setMaximumSize(QSize(16777215, 32))
        self.hostField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.hostField.setObjectName("hostField")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.hostField)
        self.portLabel = QLabel(parent=self.formLayoutWidget)
        self.portLabel.setMinimumSize(QSize(65, 32))
        self.portLabel.setMaximumSize(QSize(65, 32))
        self.portLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.portLabel)
        self.portField = QLineEdit(parent=self.formLayoutWidget)
        self.portField.setMinimumSize(QSize(0, 32))
        self.portField.setMaximumSize(QSize(16777215, 32))
        self.portField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.portField.setObjectName("portField")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.portField)
        self.schemaLabel = QLabel(parent=self.formLayoutWidget)
        self.schemaLabel.setMinimumSize(QSize(65, 32))
        self.schemaLabel.setMaximumSize(QSize(16777215, 32))
        self.schemaLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.schemaLabel.setObjectName("schemaLabel")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.schemaLabel)
        self.schemaField = QLineEdit(parent=self.formLayoutWidget)
        self.schemaField.setMinimumSize(QSize(0, 32))
        self.schemaField.setMaximumSize(QSize(16777215, 32))
        self.schemaField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.schemaField.setObjectName("schemaField")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.schemaField)
        self.usernameLabel = QLabel(parent=self.formLayoutWidget)
        self.usernameLabel.setMinimumSize(QSize(65, 32))
        self.usernameLabel.setMaximumSize(QSize(16777215, 32))
        self.usernameLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.usernameLabel)
        self.usernameField = QLineEdit(parent=self.formLayoutWidget)
        self.usernameField.setMinimumSize(QSize(0, 32))
        self.usernameField.setMaximumSize(QSize(16777215, 32))
        self.usernameField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.usernameField.setObjectName("usernameField")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.FieldRole, self.usernameField)
        self.passwordLabel = QLabel(parent=self.formLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLabel.sizePolicy().hasHeightForWidth())
        self.passwordLabel.setSizePolicy(sizePolicy)
        self.passwordLabel.setMinimumSize(QSize(65, 32))
        self.passwordLabel.setMaximumSize(QSize(65, 32))
        self.passwordLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(4, QFormLayout.ItemRole.LabelRole, self.passwordLabel)
        self.passwordField = QLineEdit(parent=self.formLayoutWidget)
        self.passwordField.setMinimumSize(QSize(0, 32))
        self.passwordField.setMaximumSize(QSize(16777215, 32))
        self.passwordField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.passwordField.setEchoMode(QLineEdit.EchoMode.Password)
        self.passwordField.setObjectName("passwordField")
        self.formLayout.setWidget(4, QFormLayout.ItemRole.FieldRole, self.passwordField)
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cancelButton = QPushButton(parent=self.formLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setMinimumSize(QSize(0, 0))
        self.cancelButton.setMaximumSize(QSize(16777215, 16777215))
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_3.addWidget(self.cancelButton, 1, 3, 1, 1)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.okButton = QPushButton(parent=self.formLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMinimumSize(QSize(0, 0))
        self.okButton.setMaximumSize(QSize(16777215, 16777215))
        self.okButton.setBaseSize(QSize(0, 0))
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(True)
        self.okButton.setFlat(False)
        self.okButton.setObjectName("okButton")
        self.gridLayout_3.addWidget(self.okButton, 1, 1, 1, 1)
        self.formLayout.setLayout(5, QFormLayout.ItemRole.FieldRole, self.gridLayout_3)

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LINZ Schema Login"))
        self.hostLabel.setText(_translate("Dialog", "Host:"))
        self.portLabel.setText(_translate("Dialog", "Port:"))
        self.schemaLabel.setText(_translate("Dialog", "Schema:"))
        self.usernameLabel.setText(_translate("Dialog", "Username:"))
        self.passwordLabel.setText(_translate("Dialog", "Password:"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.okButton.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
