#   *******************************************************************
# -*- coding: utf-8 -*-

#   *******************************************************************
#   Updated Qt5/Qt6 imports to be used with generated file from
#   PyQt UI code generator
#   Enables either pyqt5, pyqt6 or PySide2 modules to be used
#   *******************************************************************

import importlib.util

if importlib.util.find_spec("PyQt"):
    # from PyQt import uic, loadUi
    # from PyQt import   QtCore
    from PyQt import (
        pyqt, QObject, QCoreApplication, QSettings,
        Qt, QSize, QRect, QMetaObject,
        Signal, Slot,
        QIcon, QPixmap, QImage, QFont,
        QApplication, QMainWindow, QWidget, QFrame,
        QDialog, QMessageBox, QFileDialog,
        QLayout, QFormLayout, QGridLayout,
        QVBoxLayout, QHBoxLayout,
        QSizePolicy, QSpacerItem,
        QAbstractItemView, QAbstractScrollArea, QScrollArea,
        QLabel, QLineEdit, QPlainTextEdit,
        QPushButton, QToolButton, QListWidget, QListWidgetItem,
        QProgressBar, QMenuBar, QStatusBar,
        QMenu, QAction,
        QDomDocument, QDomElement, QTextCursor)
else:
    # from .PyQt import uic, loadUi
    # from .PyQt import   QtCore
    from .PyQt import (
        pyqt, QObject, QCoreApplication, QSettings,
        Qt, QSize, QRect, QMetaObject,
        Signal, Slot,
        QIcon, QPixmap, QImage, QFont,
        QApplication, QMainWindow, QWidget, QFrame,
        QDialog, QMessageBox, QFileDialog,
        QLayout, QFormLayout, QGridLayout,
        QVBoxLayout, QHBoxLayout,
        QSizePolicy, QSpacerItem,
        QAbstractItemView, QAbstractScrollArea, QScrollArea,
        QLabel, QLineEdit, QPlainTextEdit,
        QPushButton, QToolButton, QListWidget, QListWidgetItem,
        QProgressBar, QMenuBar, QStatusBar,
        QMenu, QAction,
        QDomDocument, QDomElement, QTextCursor)

#   *******************************************************************
# Form implementation generated from reading ui file 'linz_schema_create_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(Qt.WindowModality.ApplicationModal)
        Dialog.resize(600, 150)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QSize(600, 150))
        Dialog.setMaximumSize(QSize(600, 150))
        self.formLayout = QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.schemaLabel = QLabel(parent=Dialog)
        self.schemaLabel.setMinimumSize(QSize(65, 32))
        self.schemaLabel.setMaximumSize(QSize(16777215, 32))
        self.schemaLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.schemaLabel.setObjectName("schemaLabel")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.schemaLabel)
        self.schemaField = QLineEdit(parent=Dialog)
        self.schemaField.setMinimumSize(QSize(0, 32))
        self.schemaField.setMaximumSize(QSize(16777215, 32))
        self.schemaField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.schemaField.setObjectName("schemaField")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.schemaField)
        self.descriptionLabel = QLabel(parent=Dialog)
        self.descriptionLabel.setMinimumSize(QSize(65, 32))
        self.descriptionLabel.setMaximumSize(QSize(16777215, 32))
        self.descriptionLabel.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.descriptionLabel)
        self.descriptionField = QLineEdit(parent=Dialog)
        self.descriptionField.setMinimumSize(QSize(0, 32))
        self.descriptionField.setMaximumSize(QSize(16777215, 32))
        self.descriptionField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.descriptionField.setObjectName("descriptionField")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.descriptionField)
        self.gridLayout = QGridLayout()
        self.gridLayout.setContentsMargins(5, -1, 5, -1)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.okButton = QPushButton(parent=Dialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMinimumSize(QSize(0, 0))
        self.okButton.setMaximumSize(QSize(16777215, 16777215))
        self.okButton.setBaseSize(QSize(0, 34))
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(True)
        self.okButton.setFlat(False)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 2, 1, 1, 1)
        self.cancelButton = QPushButton(parent=Dialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setMinimumSize(QSize(0, 0))
        self.cancelButton.setMaximumSize(QSize(16777215, 16777215))
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 2, 1, 1)
        spacerItem1 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.formLayout.setLayout(2, QFormLayout.ItemRole.FieldRole, self.gridLayout)

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GIS Schema Name"))
        self.schemaLabel.setText(_translate("Dialog", "Schema:"))
        self.descriptionLabel.setText(_translate("Dialog", "Description:"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
